### ISSUE TITLE
Error: Resource {app-service-name} doesn't exist (but it definitely does)

### ISSUE THREAD

**Issue by donniehale-awh** [Azure/webapps-deploy#227]
The output from the `azure/webapps-deploy@v2` step is:

```sh
Error: Deployment Failed with Error: Error: Resource my-api-app doesn't exist.
```

(Resource names changed, but I've done string comparisons.)

I'm using the same workflow yaml in this product/repository as I'm using in another one where it's working fine - pretty straightforward:

```yaml
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

    # Hopefully temporary
    # Got an error in the next step (webapps-deploy) that the app service doesn't exist...
    # But it does, and this command will hopefully verify that it's visible via the prevous azure/login
    # and that it can be seen via its name.
    - name: Verify app service
      run: |
        az webapp config appsettings list --name my-api-app --resource-group my-api-dev-rg --subscription {subscription-id}

    - name: Deploy to Development environment
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.update_env.outputs.API_APP_SERVICE_NAME }}
        package: ${{ github.workspace }}/${{ env.API_PUBLISH_PATH }}
```

I know that the login works and that the app service exists because the `az` command in the `Verify app service` step succeeds and gives this output:

```json
[
  ***
    "name": "ASPNETCORE_ENVIRONMENT",
    "slotSetting": false,
    "value": "Development"
  ***,
  ***
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "slotSetting": false,
    "value": "value-redacted"
  ***,
  ***
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "slotSetting": false,
    "value": "InstrumentationKey=value-redacted"
  ***,
  ***
    "name": "APPINSIGHTS_PROFILERFEATURE_VERSION",
    "slotSetting": false,
    "value": "1.0.0"
  ***,
  ***
    "name": "APPINSIGHTS_SNAPSHOTFEATURE_VERSION",
    "slotSetting": false,
    "value": "1.0.0"
  ***
]
```

I honestly don't know what more I can do to troubleshoot this or to achieve a workaround.

Any input from anyone? Thanks.

**Comment by donniehale-awh** [comment]
I didn't change anything, but this seems to have resolved itself. I set the `ACTIONS_STEP_DEBUG` secret to `true` to see if it would yield any information. Then I re-ran the failed job (second of a two-job workflow). The job succeeded, and the app worked in the app service.

So I deleted that secret and re-ran the previously failed (but now just succeeded) job. It succeeded.

Then I re-ran the entire workflow, and it succeeded.

Finally, I merged a change to `main` so that the workflow would be automatically triggered. The workflow succeeded, and the change was visible in the newly-deployed app.

So I'm not sure what happened between yesterday and today. It had already been over 3 hours after the app service was created before the workflow tried to deploy to it and failed. Maybe some time was needed for the results of the `az ad sp crreate-for-rbac...` command to "take effect"???

Anyway, for now it's resolved.

**Comment by mskuratowski** [comment]
Hi,

I'm facing the same issues as @donniehale-awh. I set `ACTIONS_STEP_DEBUG` secret to `true `but it still doesn't work in my case.

**Comment by darena-patrick** [comment]
I'm also having this issue. I turn on GitHub Actions debugging and call the same management.azure.com API that it says it's calling and I get a result... but GitHub actions doesn't get the result for whatever reason. I have 7 other Web Apps deploying using the same service principal in the same resource group in the same subscription. It has been hours since I created these app services. Some times it works later on after performing no changes... but it is very hard to predict. Is there some sort of caching of results from the management.azure.com API or something? Any suggestions from the dev team?

**Comment by kiranpradeep** [comment]
This is a closed issue, but it exists. I faced this issue yesterday, added ACTIONS_STEP_DEBUG, it kept failing still.

Today, it is working without any further changes.

**Comment by runeheidem** [comment]
I know it's closed, but posting for posterity if anyone can use it.

We have experienced this issue extensively. Some days it's worse than others.
We have previously deployed using the service principal, and still does, but with this 'minor' change.

Can't conclude anything yet, as this issue could still resurface in our pipeline, but since I've added a step to retrieve publishing profile with az cli prior, and then reusing that profile as input in the azure/webapps-deploy@v2 it seems we haven't experienced the issue. I know it seems it shouldn't work that way when using a service principal, but it's the only thing we have seen work. I've tried with suggested 'pause steps' between IaC and deployment, up- and out scaling resources, but it doesn't work every time.

However, this seems to work (for now). 
Insert correct references for your use.

`     - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ A }}

    - name: Get app publish profile
      id: getpublishprofile
      uses: azure/CLI@v1
      with:
        inlineScript: |
          publishprofile=$(az webapp deployment list-publishing-profiles \
            --name "${{ B }}" \
            --resource-group "${{ C }}" \
            --subscription "${{ D }}" \
            --xml)
          echo "publishprofile=$publishprofile" >> $GITHUB_OUTPUT
          
      - name: Azure WebApp (Blazor) Deploy
        id: deploy-blazor-to-appservice
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ B }}
          slot-name: ${{ E }}
          publish-profile: ${{ steps.getpublishprofile.outputs.publishprofile}}
          package: ./X/Y
`

Consider adding a step to reset publishing profile afterwards, if you debug settings lets the step print the profile.
