### ISSUE TITLE
Deploy to Azure Web App is stuck on 'Package deployment using ZIP Deploy initiated.'

### ISSUE THREAD

**Issue by Mehoff** [Azure/webapps-deploy#338]
Arond two weeks ago, my deploymens to Azure Web App started working unexpectedly, and I am not alone with this issue, there is a topic on [Learn Microsoft](https://learn.microsoft.com/en-us/answers/questions/1261639/github-actions-deployment-stuck-to-package-deploym?page=1&orderby=helpful&comment=answer-1249241#newest-answer-comment) about it, but it did not get any attention, so I thought that it would be nice to post an issue here.

Basically, 'Package deployment using ZIP Deploy initiated.' is freezed in actions, and fails without any additional error after 6 hours of working. Interesting thing is that code update works fine, and Web App is building and running as expected after Oryx build finishes correctly. But before new push/deployment I have to manually cancel action, in Deployment Center of Actions tab in repo, because otherwise I will get 409 Error Conflict message in deployment action, which is annoying.
![image](https://github.com/Azure/webapps-deploy/assets/44639162/1a61e7c6-ffa4-4d79-821b-10c9da45155d)

Here is what I am getting right now in Github Actions page:
![image](https://github.com/Azure/webapps-deploy/assets/44639162/fe12d2c0-da2a-459e-a786-ae69cd3840c0)

Here is what I am seeing in Deployment Center. As you can see, last commit has status 'Success (Active)', but Build has status 'in Progress'.
![image](https://github.com/Azure/webapps-deploy/assets/44639162/fc921415-31bd-4121-b65c-dd943e440ea6)

I am not very familiar with Oryx, but it builds my application successfully. If I open 'App Logs' -> 'Running oryx build... Show logs', I see successful build of my application:
![image](https://github.com/Azure/webapps-deploy/assets/44639162/1f67a2cc-7fd7-4ab4-8927-5cf6d4b23fcf)

Last message in this log:
`Deployment successful. deployer = GITHUB_ZIP_DEPLOY deploymentPath = ZipDeploy. Extract zip.`

What I've tried:
Using different versions of webapps/deploy (v2, v2.29)
Using different versions of actions/checkout(v2, v3), actions/setup-node(v2, v3)
Using different workflow files (including base workflow file that Azure ships on Node.js App Platform Deployments configuration). I can list them in comments, if someone will ask for at.

My Web App configuration:
```
Publishing model: Code
Runtime Stack: Node - 16-lts
SKU and size: PremiumV3 (P1v3)
OS: Linux
Region: West Europe
Single deployment slot - 'Production', using default configuration on this one.
```
I did not try to delete Web App and create new one from scratch, I hope there is a possibility to fix this issue without this step. Thanks everyone for reading this, if you consider helping out - ask me for any information that is needed from me! Peace!

**Comment by roklenardic** [comment]
We are seeing exactly the same deploying a web app (not a function), Github deploy hangs for 6h:
![image](https://github.com/Azure/webapps-deploy/assets/121102/32560e1d-ff36-4856-9380-e01f1121c721)
...even though the actual deployment completed successfully:
![image (1)](https://github.com/Azure/webapps-deploy/assets/121102/1f087c3c-4f7b-482f-bab7-7f7064801b9f)

It's a Linux app service instance if that makes a difference and it started happening about 1-2weeks ago on about 50% of the time if not more often.

**Comment by Mehoff** [comment]
Basically, there is no single answer to the question how to fix this, but I will try to describe steps, how I fixed it myself today. I had two Web Apps with the same issue which is described above. First one being Strapi application (Node.js v16) second one - Next.js (Node.js v14). 

First one was fixed with these steps:
- Go to Web App
- Deployment Center
- Settings -> Source -> Disconnect
- Save workflow file -> OK (below is my deployment workflow file which is working fine)

After these steps, try to trigger workflow again (by push, for example). If deployment was successful, try to link source (Github Action) again from Deployment Center Settings. Don't forget to tick "use existing workflow file"

Problem with second Web App (Next.js) was tricky. Solution above did not help, but showed me logs on webapp/deploy@v2 step. I was able to get logs, they were looking like this: 

```
##[debug][GET] [https://<your-website>.scm.azurewebsites.net:443/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-05-10_19-27-49Z](<your-website>.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-05-10_19-27-49Z)
##[debug]POLL URL RESULT: {"statusCode":202,"statusMessage":"Accepted","headers":{"content-length":"832","connection":"close","content-type":"application/json; charset=utf-8","date":"Wed, 10 May 2023 19:29:24 GMT","server":"Kestrel","location":"[<your-website>.scm.azurewebsites.net:80/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-05-10_19-27-49Z](<your-website>.scm.azurewebsites.net/api/deployments/latest?deployer=GITHUB_ZIP_DEPLOY&time=2023-05-10_19-27-49Z)"},"body":{"id":"foobar","status":0,"status_text":"Building and Deploying 'foobar'.","author_email":"N/A","author":"N/A","deployer":"GITHUB_ZIP_DEPLOY","message":"{\"type\":\"deployment\",\"sha\":\"sha\",\"repoName\":\"reponame\",\"actor\":\"actor\",\"slotName\":\"Production\",\"commitMessage\":\"commitMessage\"}","progress":"","received_time":"2023-05-10T19:28:13.1951583Z","start_time":"2023-05-10T19:28:14.6729939Z","end_time":null,"last_success_end_time":null,"complete":false,"active":false,"is_temp":false,"is_readonly":true,"url":null,"log_url":null,"site_name":"<your-website>","build_summary":{"errors":[],"warnings":[]}}}
##[debug]Deployment status: 0 'Building and Deploying 'id'.'. retry after 5 seconds 
``` 

I saw that SHA of commit, and commit message, were not matching my current latest commit on `main` , but they were matching with failed deployment from two days ago 🥲. I am not sure why this happened, but it is really weird. I think that because status of this deployment was not chaning (ofcourse, because it had already failed 2 days ago) action was pooling status, and getting 'in progress' status all the time. Considering that I just cannot delete deploy manually from Azure UI, I used SSH in Azure panel to do so.

I took failed deployment commit id from Azure from here:
![image](https://github.com/Azure/webapps-deploy/assets/44639162/ce4915ce-254d-45b8-81a6-174d3330844f)

Portal Azure -> SSH -> `/home/site/deployments/<commit id>`

I copied this directory to root, so if something go wrong - I can bring this commit back. After that I deleted directory from `.../deployments/<commit id>`

Next deploy was successful. If I will encounter same problem in near future, I will post update on it here. Here is sneak peak into my Node.js 16 workflow file, if someone is curious:

```
name: Deploy Node.js to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: my-web-app # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x' # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm prune --production
          npm install
          npm run build --if-present
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_********* }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
```

Hope this was helpful to someone! 🙂

**Comment by shpraka** [comment]
@Mehoff @roklenardic Apologies for the inconvenience. Could you please share the app names if the issue persists so that we can look into the logs from our side and debug it further?

**Comment by Mehoff** [comment]
@shpraka For now, deployments are working fine. Unfortunately, I can't publically share app name (NDA). I think that we can close this issue? I guess if something weird will happen again, I will open a new one.

**Comment by shpraka** [comment]
Sure. I can understand you can't publically share app name. However getting more information about the symptoms help us resolve the issue. 


Closing this issue for now, feel free to create new one if something doesn't work as expected.

**Comment by jochenschroeer** [comment]
@shpraka  it still happens and we have the same issue that zip deployment for azure function app (linux) in an Azure DevOps pipeline got stuck. we use this task and we also stop the function before deploying 

  - task: AzureFunctionApp@2
    inputs:
      connectedServiceNameARM: "$(devSubscription)"
      appType: functionAppLinux
      appName: "${{ parameters.appName }}"
      package: $(Pipeline.Workspace)/drop/${{ parameters.builtPackageName }}

Disconnecting helps as suggested in earlier comments of this issue, but for sure this should not be a solution and is not a good CI / CD experience if you need to go to portal and do Disconnect in the Deployment Center.. any help is appreciated
